# Project Name
TARGET = GettingStarted

# Sources
CPP_SOURCES = GettingStarted.cpp \
$(wildcard Effect/*.cpp) \
$(wildcard Ui/Page/*.cpp) \
#$(wildcard Ui/Color/*.cpp)


# Library Locations
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
